### ISSUE TITLE
Can't start storybook script

### ISSUE THREAD

**Issue by Delagardi** [stripe/react-stripe-js#165]
Hey!

I want to look at examples. But can't start storybook script and getting the following error. As far as I can see there are no lodash in `package.json`.

```
$ start-storybook -p 6006
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './_copyObject'
Require stack:
- E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\lodash\assignIn.js
- E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\lodash\extend.js
- E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\inquirer\lib\ui\baseUI.js
- E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\inquirer\lib\ui\bottom-bar.js
- E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\inquirer\lib\inquirer.js
- E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\@storybook\core\dist\server\build-dev.js
- E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\@storybook\core\server.js
- E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\@storybook\react\dist\server\index.js
- E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\@storybook\react\bin\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\lodash\assignIn.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\Work\eze.tech\swag\misc-swag\react-stripe-js\node_modules\lodash\extend.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\Work\\eze.tech\\swag\\misc-swag\\react-stripe-js\\node_modules\\lodash\\assignIn.js',
    'E:\\Work\\eze.tech\\swag\\misc-swag\\react-stripe-js\\node_modules\\lodash\\extend.js',
    'E:\\Work\\eze.tech\\swag\\misc-swag\\react-stripe-js\\node_modules\\inquirer\\lib\\ui\\baseUI.js',
    'E:\\Work\\eze.tech\\swag\\misc-swag\\react-stripe-js\\node_modules\\inquirer\\lib\\ui\\bottom-bar.js',
    'E:\\Work\\eze.tech\\swag\\misc-swag\\react-stripe-js\\node_modules\\inquirer\\lib\\inquirer.js',
    'E:\\Work\\eze.tech\\swag\\misc-swag\\react-stripe-js\\node_modules\\@storybook\\core\\dist\\server\\build-dev.js',
    'E:\\Work\\eze.tech\\swag\\misc-swag\\react-stripe-js\\node_modules\\@storybook\\core\\server.js',
    'E:\\Work\\eze.tech\\swag\\misc-swag\\react-stripe-js\\node_modules\\@storybook\\react\\dist\\server\\index.js',
    'E:\\Work\\eze.tech\\swag\\misc-swag\\react-stripe-js\\node_modules\\@storybook\\react\\bin\\index.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Steps to reproduce:
1. Install dependencies with `yarn`
2. Try to start storybook to look at examples: `yarn storybook`

What I'm doing wrong?

P. S. I have win10 btw.

**Comment by christopher-stripe** [comment]
Hi @Delagardi, I was unable to reproduce this issue. I'm not quite sure what's wrong—maybe the `node_modules` state was corrupted somehow? What happens if you remove the `node_modules` folder completely and run a fresh `yarn` install?
